services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-gif-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: docker-gif-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3308"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
