version: '3.8'

services:
  app:
<<<<<<< HEAD
    image: moshelederman/stars:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
=======
    image: moshelederman/docker-gif-app:latest
>>>>>>> f3b94327c5cde89413151208e57bca6e7ed40638
    container_name: docker-gif-app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - app_network
    

  db:
    image: moshelederman/docker-gif-db:latest
    container_name: docker-gif-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
